name: Test (Linux ARM64)

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/baseline/**'
      - '**/benchData.json'
      - '.gitignore'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run Tests on Linux ARM64
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Clone Dependency wedb
        run: |
          git clone --depth=1 https://github.com/webc-site/wedb.git ../wedb

      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest

      - name: Run Tests
        run: |
          chmod +x ./test.sh
          ./test.sh
